// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.6
// source: api/v1/enum.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateSchemaStatus int32

const (
	// Used in case when send schema is valid
	ValidateSchemaStatus_STATUS_VALID ValidateSchemaStatus = 0
	// Used in case when send schema is invalid, e.g. field is missing, wrong type
	ValidateSchemaStatus_STATUS_INVALID ValidateSchemaStatus = 1
)

// Enum value maps for ValidateSchemaStatus.
var (
	ValidateSchemaStatus_name = map[int32]string{
		0: "STATUS_VALID",
		1: "STATUS_INVALID",
	}
	ValidateSchemaStatus_value = map[string]int32{
		"STATUS_VALID":   0,
		"STATUS_INVALID": 1,
	}
)

func (x ValidateSchemaStatus) Enum() *ValidateSchemaStatus {
	p := new(ValidateSchemaStatus)
	*p = x
	return p
}

func (x ValidateSchemaStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateSchemaStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_enum_proto_enumTypes[0].Descriptor()
}

func (ValidateSchemaStatus) Type() protoreflect.EnumType {
	return &file_api_v1_enum_proto_enumTypes[0]
}

func (x ValidateSchemaStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateSchemaStatus.Descriptor instead.
func (ValidateSchemaStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_enum_proto_rawDescGZIP(), []int{0}
}

var File_api_v1_enum_proto protoreflect.FileDescriptor

var file_api_v1_enum_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2a, 0x3c, 0x0a, 0x14, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x42, 0x32, 0x5a, 0x30, 0x68, 0x74, 0x74,
	0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x76, 0x36, 0x35, 0x6b, 0x72, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2d, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_enum_proto_rawDescOnce sync.Once
	file_api_v1_enum_proto_rawDescData = file_api_v1_enum_proto_rawDesc
)

func file_api_v1_enum_proto_rawDescGZIP() []byte {
	file_api_v1_enum_proto_rawDescOnce.Do(func() {
		file_api_v1_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_enum_proto_rawDescData)
	})
	return file_api_v1_enum_proto_rawDescData
}

var file_api_v1_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_enum_proto_goTypes = []interface{}{
	(ValidateSchemaStatus)(0), // 0: schema_registry.api.v1.ValidateSchemaStatus
}
var file_api_v1_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_enum_proto_init() }
func file_api_v1_enum_proto_init() {
	if File_api_v1_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_enum_proto_goTypes,
		DependencyIndexes: file_api_v1_enum_proto_depIdxs,
		EnumInfos:         file_api_v1_enum_proto_enumTypes,
	}.Build()
	File_api_v1_enum_proto = out.File
	file_api_v1_enum_proto_rawDesc = nil
	file_api_v1_enum_proto_goTypes = nil
	file_api_v1_enum_proto_depIdxs = nil
}
